using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace NWayland.Generator
{
    partial class WaylandProtocolGenerator
    {
        private readonly Dictionary<string, string> _protocolFullNames = new();
        private readonly Dictionary<string, string> _protocolNamespaces = new();
        private readonly Dictionary<NwgSourceText, WaylandProtocol> _protocols = new();
        private readonly EquatableArray<NwgArrayTypeMapping> _arrayMappings;

        public WaylandProtocolGenerator(NwgInputModel model)
        {
            _arrayMappings = model.ArrayMappings;
            foreach(var externalMapping in model.ExternalTypeMappings)
            {
                // TODO gracefully handle name conflicts
                _protocolFullNames.Add(externalMapping.Name, externalMapping.FullTypeName);
            }
            foreach (var src in model.Sources)
            {
                var p = WaylandProtocol.ParseXml(src.Source);
                _protocols[src] = p;
                var ns = $"{src.Namespace}.{Pascalize(p.Name)}";

                _protocolNamespaces.Add(p.Name, ns);
                
                foreach (var i in p.Interfaces)
                {
                    var fullName = $"{ProtocolNamespace(p.Name)}.{Pascalize(i.Name)}";
                    if (_protocolFullNames.ContainsKey(i.Name))
                    {
                        
                        throw new NwGeneratorWithFileException(src.Path,
                            $"Can't add {i.Name} from {p.Name}, {i.Name} is already associated to {_protocolFullNames[i.Name]}");
                    }

                    _protocolFullNames.Add(i.Name, fullName);
                }
            }
        }
        
        
        public static void GenerateModel(NwgInputModel nwgInputModel, Action<string, string> addSource)
        {
            var gen = new WaylandProtocolGenerator(nwgInputModel);
            var rv = new Dictionary<string, string>();
            foreach (var p in gen._protocols)
            {
                addSource(p.Value.Name, gen.Generate(p.Value));
            }
        }

        private WaylandProtocol? _currentProtocol;
        Exception CreateError(string message)
        {
            if (_currentProtocol == null)
                return new NwGeneratorException(message);
            else
                return new NwGeneratorWithFileException(message,
                    _protocols.First(x => x.Value == _currentProtocol).Key.Path);
        }
        
        string Generate(WaylandProtocol protocol)
        {
            if (_currentProtocol != null)
                throw new InvalidOperationException("Reentrancy");
            _currentProtocol = protocol;
            try
            {
                var unit = CompilationUnit();
                unit = Generate(unit, protocol);

                return unit.NormalizeWhitespace("    ").ToFullString().Replace("//CRLF", "");
            }
            finally
            {
                _currentProtocol = null;
            }
            /*
            var cw = new AdhocWorkspace();
            var formatted = Formatter.Format(unit, cw, cw.Options
                .WithChangedOption(CSharpFormattingOptions.NewLineForMembersInObjectInit, true)
                .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInObjectCollectionArrayInitializers, true)
                .WithChangedOption(CSharpFormattingOptions.NewLineForMembersInAnonymousTypes, true)
                .WithChangedOption(CSharpFormattingOptions.NewLinesForBracesInMethods, true)
            );

            return formatted.ToFullString();*/
        }

        private CompilationUnitSyntax Generate(CompilationUnitSyntax code, WaylandProtocol protocol)
        {
            code = code.AddUsings(UsingDirective(IdentifierName("System")))
                .AddUsings(UsingDirective(IdentifierName("System.Runtime.CompilerServices")))
                .AddUsings(UsingDirective(IdentifierName("System.Runtime.InteropServices")))
                .AddUsings(UsingDirective(IdentifierName("NWayland.Protocols.Wayland")))
                .AddUsings(UsingDirective(IdentifierName("NWayland.Interop")));

            var ns = NamespaceDeclaration(ProtocolNamespaceSyntax(protocol.Name))
                .WithLeadingTrivia(
                    TriviaList(
                        Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)),
                        Comment("// <auto-generated/>")))
                .NormalizeWhitespace();

            foreach (var @interface in protocol.Interfaces)
            {
                var cl = ClassDeclaration(Pascalize(@interface.Name))
                    .WithModifiers(new SyntaxTokenList(
                        Token(SyntaxKind.PublicKeyword),
                        Token(SyntaxKind.SealedKeyword),
                        Token(SyntaxKind.UnsafeKeyword),
                        Token(SyntaxKind.PartialKeyword)))
                    .AddBaseListTypes(
                        SimpleBaseType(ParseTypeName("WlProxy")));
                cl = WithSummary(cl, @interface.Description);
                cl = WithSignature(cl, @interface);
                cl = WithRequests(cl, protocol, @interface);
                cl = WithEvents(cl, protocol, @interface);
                cl = WithEnums(cl, protocol, @interface);
                cl = WithFactory(cl, @interface)
                    .AddMembers(DeclareConstant("string", "InterfaceName", MakeLiteralExpression(@interface.Name)))
                    .AddMembers(DeclareConstant("int", "InterfaceVersion", MakeLiteralExpression(@interface.Version)));

                var ctor = ConstructorDeclaration(cl.Identifier)
                    .AddModifiers(Token(SyntaxKind.PublicKeyword))
                    .WithParameterList(ParameterList(
                        SeparatedList(new[]
                        {
                            Parameter(Identifier("handle")).WithType(ParseTypeName("IntPtr")),
                            Parameter(Identifier("version")).WithType(ParseTypeName("int"))
                        }))).WithBody(Block())
                    .WithInitializer(ConstructorInitializer(SyntaxKind.BaseConstructorInitializer,
                        ArgumentList(SeparatedList(new[]
                        {
                            Argument(IdentifierName("handle")),
                            Argument(IdentifierName("version"))
                        }))));
                cl = cl.AddMembers(ctor);
                cl = cl.AddMembers(ConstructorDeclaration(cl.Identifier)
                    .AddModifiers(Token(SyntaxKind.PrivateKeyword))
                    .WithParameterList(ParameterList(
                        SeparatedList(new[]
                        {
                            Parameter(Identifier("context")).WithType(ParseTypeName("WlProxyContext")),
                            Parameter(Identifier("handle")).WithType(ParseTypeName("IntPtr")),
                            Parameter(Identifier("iface")).WithType(ParseTypeName("WlInterfaceDescription")),
                            Parameter(Identifier("ownsHandle")).WithType(ParseTypeName("bool"))
                        }))).WithBody(Block())
                    .WithInitializer(ConstructorInitializer(SyntaxKind.BaseConstructorInitializer,
                        ArgumentList(SeparatedList(new[]
                        {
                            Argument(IdentifierName("context")),
                            Argument(IdentifierName("handle")),
                            Argument(IdentifierName("iface")),
                            Argument(IdentifierName("ownsHandle"))
                        })))));

                ns = ns.AddMembers(cl);
            }

            return code.AddMembers(ns);
        }
    }
}
